### ISSUE TITLE
Flatpak/Appimage/Snap support

### ISSUE THREAD

**Issue by Aman9das** [omegaui/app_fleet#11]
Any of the above packaging would reduce the user's reliance on manual updates on custom scripts.

**Comment by omegaui** [comment]
Yes, I'm planning to do **flatpak** packaging.
Currently, on Ubuntu 22.10 (no further updates available, so I'm unable to install flatpak).
I'll migrate to Fedora 38 this weekend.
And, will then, do the flatpak packaging.

Thank you for proposing this enhancement.

**Comment by omegaui** [comment]
## Snap/Flatpak Packaging Unsupported

App Fleet being a workspace launch automation tool requires **system wide read access**,
the reason is very justifying:
- App Fleet not only launches **Apps** but also **any custom script** the user wants
and this script can exist anywhere on the drive or even on the **external** drive.
- Snap Packaging isn't possible as packaging a flutter app with snap requires **gnome** extension which in turn doesn't supports **classic** confinement, and App Fleet cannot leverage the full system in a **strict** confinement. (I searched a lot about building it under **classic** confinement to get system wide read access but didn't find any way to do it. Any help on this is highly appreciated.)
- Flatpak Packaging also isn't supported as flatpaks have additional set of hindrance, the `/usr` directory is **inaccessible** by a flatpak app, and this is the core directory around which App Fleet detects apps and system icons.
Not only `/usr` but directories like `/var` where the installed flatpak's metainfo resides is inaccessible, thus, App Fleet won't be able to detect other apps.

Both Snaps and Flatpaks are launched in a **SANDBOX**, and App Fleet needs to be directly invoked on the system to be able to do what it is meant to do.

> As far as **AppImage** is considered, the sole cause why I planned for packaging was to roll out updates through the native software updater and not by making the user to rerun the update command everytime an update arrives. <br>

Current network installers included on home repo provide a much seamless install and update experience to the users.
Also, the next release of App Fleet will include a **Self Updatation System** and **In-App Uninstall Option**.
